Repository sonata-project/exporter, pull requests merged in 2021-09, with the labels that each got.

#514 Add static analysis
  .github/workflows/qa.yaml
  Makefile
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
  src/Source/AbstractPropertySourceIterator.php
  src/Source/AbstractXmlSourceIterator.php
  tests/Source/AbstractPropertySourceIteratorTest.php
  tests/Source/IteratorSourceIteratorTest.php
  tests/Source/XmlExcelSourceIteratorTest.php
  tests/Writer/JsonWriterTest.php
  tests/Writer/SitemapWriterTest.php
Labels: patch

#518 Minor fixes
  composer.json
  src/Source/AbstractPropertySourceIterator.php
  src/Source/AbstractXmlSourceIterator.php
  src/Source/ChainSourceIterator.php
  src/Source/CsvSourceIterator.php
  src/Source/DoctrineODMQuerySourceIterator.php
  src/Source/DoctrineORMQuerySourceIterator.php
  src/Source/IteratorCallbackSourceIterator.php
  src/Source/IteratorSourceIterator.php
  src/Source/PDOStatementSourceIterator.php
Labels: minor

#531 Update homepage
  composer.json
Labels: pedantic

#533 Add conflict with doctrine/orm < 2.8
  composer.json
Labels: patch

#532 Deprecate SourceIteratorInterface
  src/Source/SourceIteratorInterface.php
Labels: minor
