Repository sonata-project/exporter, pull requests merged in 2022-05, with the labels that each got.

#581 Bump phpstan and psalm
  phpstan.neon.dist
  psalm.xml
  src/Bridge/Symfony/Bundle/SonataExporterBundle.php
  src/Bridge/Symfony/DependencyInjection/Configuration.php
  src/Bridge/Symfony/DependencyInjection/SonataExporterExtension.php
  src/Exporter.php
  src/Source/AbstractXmlSourceIterator.php
  src/Source/ArraySourceIterator.php
  src/Source/CsvSourceIterator.php
  src/Source/DoctrineORMQuerySourceIterator.php
  src/Source/PropelCollectionSourceIterator.php
  src/Source/SymfonySitemapSourceIterator.php
  src/Writer/CsvWriter.php
  src/Writer/FormattedBoolWriter.php
  src/Writer/GsaFeedWriter.php
  src/Writer/InMemoryWriter.php
  src/Writer/SitemapWriter.php
  src/Writer/WriterInterface.php
  src/Writer/XlsWriter.php
  src/Writer/XlsxWriter.php
  src/Writer/XmlExcelWriter.php
  src/Writer/XmlWriter.php
  tests/Bridge/Symfony/DependencyInjection/ConfigurationTest.php
  tests/ExporterTest.php
  tests/Source/AbstractPropertySourceIteratorTest.php
  tests/Source/CsvSourceIteratorTest.php
  tests/Source/DoctrineODMQuerySourceIteratorTest.php
  tests/Source/DoctrineORMQuerySourceIteratorTest.php
  tests/Source/IteratorCallbackSourceIteratorTest.php
  tests/Source/IteratorSourceIteratorTest.php
  tests/Source/PDOStatementSourceIteratorTest.php
  tests/Source/PropelCollectionSourceIteratorTest.php
  tests/Source/XmlExcelSourceIteratorTest.php
  tests/Source/XmlSourceIteratorTest.php
  tests/Writer/CsvWriterTerminateTest.php
  tests/Writer/CsvWriterTest.php
  tests/Writer/FormattedBoolWriterTest.php
  tests/Writer/GsaFeedWriterTest.php
  tests/Writer/JsonWriterTest.php
  tests/Writer/SitemapWriterTest.php
  tests/Writer/XlsWriterTest.php
  tests/Writer/XlsxWriterTest.php
  tests/Writer/XmlExcelWriterTest.php
  tests/Writer/XmlWriterTest.php
Labels: minor

#584 Remove deprecated code
  UPGRADE-3.0.md
  composer.json
  docs/reference/sources.rst
  src/Bridge/Symfony/Bundle/SonataExporterBundle.php
  src/Bridge/Symfony/SonataExporterSymfonyBundle.php
  src/Source/AbstractPropertySourceIterator.php
  src/Source/AbstractXmlSourceIterator.php
  src/Source/ChainSourceIterator.php
  src/Source/CsvSourceIterator.php
  src/Source/DoctrineDBALConnectionSourceIterator.php
  src/Source/IteratorSourceIterator.php
  src/Source/PDOStatementSourceIterator.php
  src/Source/PropelCollectionSourceIterator.php
  src/Source/SourceIteratorInterface.php
  src/Source/SymfonySitemapSourceIterator.php
  src/Test/AbstractTypedWriterTestCase.php
  tests/Source/PropelCollectionSourceIteratorTest.php
Labels: major

#588 Fix some phpstan errors
  src/Source/AbstractXmlSourceIterator.php
  src/Source/CsvSourceIterator.php
  src/Writer/CsvWriter.php
  src/Writer/GsaFeedWriter.php
  src/Writer/JsonWriter.php
  src/Writer/SitemapWriter.php
  src/Writer/XlsWriter.php
  src/Writer/XmlExcelWriter.php
  src/Writer/XmlWriter.php
  tests/Source/PDOStatementSourceIteratorTest.php
  tests/Writer/CsvWriterTerminateTest.php
  tests/Writer/CsvWriterTest.php
  tests/Writer/GsaFeedWriterTest.php
  tests/Writer/SitemapWriterTest.php
  tests/Writer/XlsWriterTest.php
  tests/Writer/XmlExcelWriterTest.php
Labels: pedantic

#592 Solve phpstan issues
  src/Source/AbstractPropertySourceIterator.php
  src/Source/DoctrineODMQuerySourceIterator.php
  src/Source/DoctrineORMQuerySourceIterator.php
  src/Writer/CsvWriter.php
  src/Writer/GsaFeedWriter.php
  src/Writer/JsonWriter.php
  src/Writer/SitemapWriter.php
  src/Writer/XlsWriter.php
  src/Writer/XlsxWriter.php
  src/Writer/XmlExcelWriter.php
  src/Writer/XmlWriter.php
  tests/Source/AbstractPropertySourceIteratorTest.php
Labels: pedantic

#593 Solve phpstan/psalm issues
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/Bridge/Symfony/DependencyInjection/Configuration.php
  src/Source/AbstractXmlSourceIterator.php
  src/Source/CsvSourceIterator.php
  src/Writer/CsvWriter.php
  src/Writer/GsaFeedWriter.php
  src/Writer/JsonWriter.php
  src/Writer/SitemapWriter.php
  src/Writer/XlsWriter.php
  src/Writer/XmlExcelWriter.php
  src/Writer/XmlWriter.php
  tests/Source/DoctrineDBALConnectionSourceIteratorTest.php
  tests/Source/Fixtures/Document.php
  tests/Source/Fixtures/Entity.php
  tests/Source/IteratorCallbackSourceIteratorTest.php
Labels: pedantic

#596 Drop support of Symfony 5.3
  composer.json
Labels: minor
