Repository sonata-project/exporter, pull requests merged in 2024-06, with the labels that each got.

#669 Bump rector
  composer.json
Labels: pedantic

#670 DevKit updates for 3.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
  psalm.xml
Labels: automerge, dev-kit

#671 Solve internal class usage
  src/Bridge/Symfony/DependencyInjection/SonataExporterExtension.php
Labels: patch
